#import "definitions.typ": *

#let components = (
  component(
    manufacturer: "SCE",
    catalog: "SCE-16H1606SS6LP",
    qty: "1",
    sheet: 1,
    description: "Wall Mount Enclosure - NEMA 4X",
    tags: ("ENC",),
    specs: (
      [0.075" stainless steel type 316/316L],
      [Flange trough collar around all sides of door opening],
      [Pour in place oil and water resistant gasket],
      [Hasp and staple for padlocking],
      [Stainless steel continuous hinges],
      [Welded mounting provision top and bottom of back],
      [\#4 brushed finish on all exterior surfaces],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-16P16",
    qty: "1",
    sheet: 1,
    description: "Enclosure Back Panel",
    tags: ("ENC",),
    specs: (
      [13"H x 13"W x 0.10"D flat subpanel],
      [Powder coated white finish],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-BVKD",
    qty: "1",
    sheet: 1,
    description: "NEMA 4X VENT/DRAIN",
    tags: ("DRAIN",),
    specs: (
      [Drain and breather vent kit],
      [Made of corrosion and UV resistant polycarbonate material],
      [NEMA 4X rated],
      [10 in#sym.dot;lb installation torque],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKT38LGG31",
    qty: "1",
    sheet: 2,
    description: "PTT Light, 120VAC LED, Green",
    tags: ("LT5208",),
    specs: (
      [Plastic bezel material],
      [120VAC rated supply voltage],
      [1 C/O contact composition],
      [5000000 cycle mechanical durability],
      [0.55A rated operational current],
      [Silver alloy contact material],
      [60kA, 7200VA rated short-circuit making capacity],
      [6kA, 720VA rated breaking capacity],
      [Green fresnel polycarbonate lens],
      [Green LED],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKT38LRR31",
    qty: "1",
    sheet: 2,
    description: "PTT Light, 120VAC LED, Red",
    tags: ("LT5209",),
    specs: (
      [Plastic bezel material],
      [120VAC rated supply voltage],
      [1 C/O contact composition],
      [5000000 cycle mechanical durability],
      [0.55A rated operational current],
      [Silver alloy contact material],
      [60kA, 7200VA rated short-circuit making capacity],
      [6kA, 720VA rated breaking capacity],
      [Red fresnel polycarbonate lens],
      [Red LED],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKT38LYA31",
    qty: "1",
    sheet: 2,
    description: "PTT Light, 120VAC LED, Amber",
    tags: ("LT5210",),
    specs: (
      [Plastic bezel material],
      [120VAC rated supply voltage],
      [1 C/O contact composition],
      [5000000 cycle mechanical durability],
      [0.55A rated operational current],
      [Silver alloy contact material],
      [60kA, 7200VA rated short-circuit making capacity],
      [6kA, 720VA rated breaking capacity],
      [Amber fresnel polycarbonate lens],
      [Yellow LED],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "XB4BA922",
    qty: "1",
    sheet: 3,
    description: "Manual Overload Reset Pushbutton",
    tags: ("RESET",),
    specs: (
      [Chromium plated metal bezel],
      [Zamak fixing collar material],
      [Black flush, unmarked operator profile],
      [5.1...10.1" activating distance],
      [NEMA 4X degree of protection],
      [TH protective treatment],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKS43BH13",
    qty: "1",
    sheet: 4,
    description: "3 Position Switch, Black",
    tags: ("SS5205",),
    specs: (
      [Black standard knob operator profile],
      [Stay put operator],
      [1 C/O contact composition],
      [NEMA 4X degree of protection],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "BGL26015",
    qty: "1",
    sheet: 5,
    description: "Main Circuit Breaker, 15A",
    tags: ("CB5201",),
    specs: (
      [15A line rated current],
      [2 pole circuit breaker],
      [Toggle control type],
      [65kA breaking capacity],
      [65kA rated service breaking capcity],
      [Thermal-magnetic trip unit technology],
      [80% continuous current rating],
      [20000 cycle mechanical durability],
      [10000 cycle electrical durability],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "7940102572",
    qty: "1",
    sheet: 6,
    description: "Circuit Breaker, 120VAC, 2A",
    tags: ("CB5204",),
    specs: (
      [120VAC operating voltage],
      [2A current rating],
      [10kA interrupting capacity],
      [100M#sym.Omega insulation resistance],
      [10000 mechanical operations operating life],
      [-40...65#sym.degree;C operating temperature range],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "8536-SAO11V02ES",
    qty: "1",
    sheet: 7,
    description: "NEMA Motor Starter / Overload",
    tags: ("M5205",),
    specs: (
      [Non-reversing starter type],
      [NEMA size 00],
      [9A rated current],
      [0.33HP at 115VAC],
      [120VAC 60 Hz coil voltage],
      [Open enclosure type],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "B9.10",
    qty: "1",
    sheet: 7,
    description: "Thermal Motor Overload",
    tags: ("OL5201",),
    specs: (
      [Class 20 motor tripping class],
      [Melting alloy thermal overload type],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "9050JCK70V20",
    qty: "1",
    sheet: 9,
    description: "Repeat Cycle Timer, 0.5 Sec to 999 Hours",
    tags: ("RCT",),
    specs: (
      [120VAC operating voltage],
      [0.5 second to 999 hour programmable timing range],
      [3 VA power burden],
      [10 million mechanical operations operating life],
      [100,000 electrical operations operating life],
      [Silver nickel contact material],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "8501NR61",
    qty: "1",
    sheet: 9,
    description: "RELAY SOCKET, 120VAC, 11 PIN, DIN",
    tags: ("RCT",),
    specs: (
      [DIN rail mounted relay socket],
      [Single tiered screw clamp terminal electrical connection],
      [15A rated at 300VAC],
    ),
  ),
)

#let spare_parts = components.filter(comp => comp.catalog == "test2" or comp.catalog == "test")

#let spare_parts_qty = (
  "test": "1",
  "test2": "2"
)
