#import "definitions.typ": *

#let components = (
  component(
    manufacturer: "SCE",
    catalog: "SCE-30H2416SSLP",
    qty: "1",
    sheet: 1,
    description: "Wall Mount Enclosure - NEMA 4X",
    tags: ("ENC",),
    specs: (
      [0.075" stainless steel type 304],
      [Flange trough around all sides of door opening],
      [Oil-resistant door gasket],
      [Hasp and staple for padlocking],
      [Stainless steel continuous hinge],
      [Ground stud on door],
      [NEMA 4X rated],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-30P24",
    qty: "1",
    sheet: 1,
    description: "Enclosure Backpanel",
    tags: ("ENC",),
    specs: (
      [Bent subpanel],
      [27"H x 21"W x 0.88"D dimensions],
      [Powder coated white finish],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "7940102572",
    qty: "1",
    sheet: 2,
    description: "Circuit Breaker, 120VAC, 2A",
    tags: ("CB3203",),
    specs: (
      [240VAC operating voltage],
      [-40...85#sym.degree;C operating temperature range],
      [10kA ampere interrupting capacity],
      [2A current rating],
      [Medium time delay],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "7940102584",
    qty: "1",
    sheet: 2,
    description: "Circuit Breaker, 120VAC, 20A",
    tags: ("CB3203A",),
    specs: (
      [240VAC operating voltage],
      [-40...85#sym.degree;C operating temperature range],
      [10kA ampere interrupting capacity],
      [20A current rating],
      [Medium time delay],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "7940102582",
    qty: "2",
    sheet: 2,
    description: "Circuit Breaker, 120VAC, 15A",
    tags: ("CB3204", "CB3211",),
    specs: (
      [240VAC operating voltage],
      [-40...85#sym.degree;C operating temperature range],
      [10kA ampere interrupting capacity],
      [15A current rating],
      [Medium time delay],
    ),
  ),
  component(
    manufacturer: "Leviton",
    catalog: "T5015-W",
    qty: "1",
    sheet: 3,
    description: "Single Receptacle, 15A",
    tags: ("RECP3204",),
    specs: (
      [125VAC rated supply voltage],
      [15A rated current],
      [2-pole, 3 wire grounding],
      [White thermoplastic nylon body material],
      [Brass 8-32 grounding screw],
      [Zinc-plated steel strap material],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "RPM42F7",
    qty: "1",
    sheet: 4,
    description: "Relay, SP4T, 120VAC, 15A",
    tags: ("CR3213",),
    specs: (
      [120VAC 50/60Hz control circuit voltage],
      [15A rated operational current],
      [4 C/O contact composition],
      [With status LED and lockable test button],
      [15A load current at 250VAC],
      [100000 cycle resistive electrical durability],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "RPZF4",
    qty: "1",
    sheet: 4,
    description: "Miniature Relay Socket, 120VAC, DIN",
    tags: ("CR3213",),
    specs: (
      [\<250 VAC UL rated operational voltage],
      [16A conventional free air thermal current],
      [4 C/O contact composition],
    ),
  ),
  component(
    manufacturer: "APC",
    catalog: "SRT1000XLA",
    qty: "1",
    sheet: 5,
    description: "Uninterruptible Power Supply",
    tags: ("UPS",),
    specs: (
      [120VAC single phase main input voltage],
      [NEMA 5-15P receptacle input connection type],
      [40-70Hz auto-sensing input frequency],
      [120VAC single phase main output voltage],
      [1000VA rated power],
      [6 NEMA 5-15R receptacle outputs],
      [Built-in bypass],
      [On-line UPS, sine wave waveform type],
    ),
    misc: [
      #gen_pws_calc_table(("PLCPS",), 569, pws_components)

      #gen_load_calc_table(("UPS",), 1000, ups_components)
    ]
  ),
  component(
    manufacturer: "APC",
    catalog: "AP9614",
    qty: "1",
    sheet: 5,
    description: "Dry Contact I/O Card",
    tags: ("UPS",),
    specs: (
      [24VDC rated voltage],
      [Self powered via UPS SmartSlot],
      [0...200mA line rated current],
      [0.522ft cable length],
    ),
  ),
  component(
    manufacturer: "APC",
    catalog: "SRT48BP",
    qty: "1",
    sheet: 5,
    description: "UPS External Battery Pack",
    tags: ("BP",),
    specs: (
      [External lead-acid battery pack],
      [2U rack unit size],
      [Stand alone battery stack],
      [48VDC battery voltage],
      [2 replacement battery cartridges],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-TSH50",
    qty: "1",
    sheet: 6,
    description: "Enclosure Heater",
    tags: ("HTR3203",),
    specs: (
      [For protection from condensation],
      [Positive temperature coefficient application],
      [35mm DIN rail clip for mounting],
      [Touch safe heater, with 2 screw terminals for standard AWG 14 wire],
    ),
  ),
  component(
    manufacturer: "Finder",
    catalog: "7T.81.0.000.2403",
    qty: "1",
    sheet: 7,
    description: "Enclosure Heater Thermostat, NC",
    tags: ("THERMOSTAT",),
    specs: (
      [1 NC SPST contact configuration],
      [10A rated current, 20A maximum peak current],
      [0.3A breaking capacity at 110VAC],
      [Silver Nickel standard contact material],
      [0...60#sym.degree;C setting range],
      [7#sym.plus.minus;4K switch differential],
      [$100*10^13$ cycle electrical life at 2500VA load],
      [IP20 protection category],
      [-45...80#sym.degree;C ambient temperature range],
    ),
  ),)

#let spare_parts = components.filter(comp => comp.catalog == "test2" or comp.catalog == "test")

#let spare_parts_qty = (
  "test": "1",
  "test2": "2"
)
