#import "definitions.typ": *

#let components = (
  component(
    manufacturer: "SCE",
    catalog: "SCE-60EL3616SS6LPPL",
    qty: "1",
    sheet: 1,
    description: "NEMA 4X Wall Mount Enclosure",
    tags: ("ENC",),
    specs: (
      [0.075" stainless steel type 304],
      [Seams continuously welded and ground smooth],
      [Stainless steel concealed hinges],
      [Black zinc die cast keylocking/padlocking handles],
      [3-point latching mechanism],
      [Pour in place oil and water resistant gasket],
      [Ground stud on door and body],
      [NEMA 4X rated],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-DF60EL36LP",
    qty: "1",
    sheet: 1,
    description: "Dead Front Panel",
    tags: ("ENC",),
    specs: (
      [0.075" carbon steel],
      [Designed for use in wall mount enclosures with SCE concealed hinges],
      [Quarter turn wing knob closures],
      [Powder coated white finish inside and out],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-60P36",
    qty: "1",
    sheet: 1,
    description: "Enclosure Backpanel",
    tags: ("ENC",),
    specs: (
      [Bent Subpanel],
      [57"H x 33"W x 0.88"D dimensions],
      [Powder coated white finish],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-ELMFK4",
    qty: "1",
    sheet: 1,
    description: "Wall Mount Foot Kit",
    tags: ("ENC",),
    specs: (
      [Chemical and Corrosion resistant polyamide material],
      [NEMA 4X rated],
      [Comes with stainless steel bolt and zinc nuts],
      [Kit of four],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-BVKD",
    qty: "1",
    sheet: 1,
    description: "NEMA 4X Vent/Drain",
    tags: ("DRAIN",),
    specs: (
      [NEMA 4X rated],
      [Installed on bottom of enclosure as dual drain and vent],
      [10 inch#sym.dot;lb installation torque],
    ),
  ),
  component(
    manufacturer: "Jasco",
    catalog: "26741",
    qty: "1",
    sheet: 2,
    description: "LED Light Fixture",
    tags: ("WLT1205",),
    specs: (
      [120VAC 60Hz supply voltage],
      [3000K color temperature],
      [773 lumen brightness],
      [18"L x 3.25"W x 1.33"D dimension],
      [50,000 hours of LED life],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKT38LWW31",
    qty: "1",
    sheet: 3,
    description: "PTT Light, 120VAC LED, White",
    tags: ("LT1204",),
    specs: (
      [120VAC supply voltage],
      [Plastic bezel materal],
      [White polycarbonate fresnel lens],
      [1 C/O contact type],
      [White LED light source],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKR1B",
    qty: "1",
    sheet: 4,
    description: "Pushbutton, Black",
    tags: ("PB1219",),
    specs: (
      [Plastic bezel material],
      [Octagonal signaling unit head without light source],
      [Black operator color],
      [Flush operator profile],
      [Spring return operator],
      [NEMA 4X protection rating],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001KA2",
    qty: "1",
    sheet: 4,
    description: "1 NO Contact",
    tags: ("PB1219",),
    specs: (
      [Silver alloy contact material],
      [10A conventional free air thermal current],
      [3A at 240VAC rated operational current],
      [60kA short-circuit making capacity at 120VAC],
      [6kA rated breaking capacity at 120VAC],
      [-13...158#sym.degree;F ambient air temperature for operation],
    ),
  ),
  component(
    manufacturer: "Citel",
    catalog: "DS42S-120/G",
    qty: "1",
    sheet: 5,
    description: "Transient Voltage Surge Suppressor",
    tags: ("SPD1202",),
    specs: (
      [120VAC single phase network],
      [Common/differential modes of protection],
      [40kA total maximum discharge current],
      [-35...60#sym.degree;C ambient temperature range],
      [Disconnection via fuse-link fail-safe behavior],
      [DIN rail mounting],
      [Thermoplastic UL94-V0 material],
    ),
  ),
  component(
    manufacturer: "Phoenix Contact",
    catalog: "2866776",
    qty: "2",
    sheet: 6,
    description: "24VDC Power Supply",
    tags: ("PWS1220", "PWS1225",),
    specs: (
      [100VAC...240VAC nominal input voltage range],
      [569VA nominal power consumption],
      [92% efficiency typical (at 120VAC)],
      [24VDC #sym.plus.minus 1% nominal output voltage],
      [20A nominal output current],
      [8W maximum no-load power dissipation],
      [DIN rail mounting],
    ),
    misc: [
      #underline[Power supply load calculations]

      PWS1220 and PWS1225 are redundant

      #let total_current_draw = pws_components.values().reduce((acc, v) => float(v) + float(acc))
      #let pws_current_cap = 20

      #table(
        columns: (75%, 25%),
        align: (left, center),
        stroke: (x,y) => if y == 0 or (x == 1 and y == pws_components.len()) {(bottom: 1pt)} else {none},
        table.header([Description], [Current Draw #linebreak() (Amps)]),
        ..pws_components.pairs().flatten(),
        table.cell(align: right, [Total Current Draw]), [#total_current_draw]
      )

      #let perc_use = total_current_draw/pws_current_cap * 100

      #list(indent: 1em)[$"Total current capacity" = #total_current_draw/#pws_current_cap", "#perc_use% "used"$] 
    ]
  ),
  component(
    manufacturer: "Phoenix Contact",
    catalog: "2320157",
    qty: "1",
    sheet: 7,
    description: "24VDC Power Supply Redundancy Module",
    tags: ("PWS1232",),
    specs: (
      [12...24VDC nominal input voltage range],
      [>97% output efficiency],
      [20A nominal redundancy output current],
      [10W power loss nominal load max],
      [DIN rail mounting],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "7940102584",
    qty: "1",
    sheet: 8,
    description: "Circuit Breaker, 120VAC, 20A",
    tags: ("CB1202",),
    specs: (
      [240VAC operating voltage],
      [-40...85#sym.degree;C operating temperature range],
      [10kA ampere interrupting capacity],
      [20A current rating],
      [Medium time delay],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "7940102579",
    qty: "2",
    sheet: 8,
    description: "Circuit Breaker, 120VAC, 1A",
    tags: ("CB1211", "CB1213",),
    specs: (
      [240VAC operating voltage],
      [-40...85#sym.degree;C operating temperature range],
      [10kA ampere interrupting capacity],
      [1A current rating],
      [Medium time delay],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "7940102582",
    qty: "4",
    sheet: 8,
    description: "Circuit Breaker, 120VAC, 15A",
    tags: ("CB1205", "CB1208", "CB1220", "CB1225",),
    specs: (
      [240VAC operating voltage],
      [-40...85#sym.degree;C operating temperature range],
      [10kA ampere interrupting capacity],
      [15A current rating],
      [Medium time delay],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "7940102572",
    qty: "1",
    sheet: 8,
    description: "Circuit Breaker, 120VAC, 2A",
    tags: ("CB1218",),
    specs: (
      [240VAC operating voltage],
      [-40...85#sym.degree;C operating temperature range],
      [10kA ampere interrupting capacity],
      [2A current rating],
      [Medium time delay],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "7940102624",
    qty: "2",
    sheet: 8,
    description: "Circuit Breaker, 24VDC, 1A",
    tags: ("CB1421", "CB1437",),
    specs: (
      [80VDC operating voltage],
      [-40...85#sym.degree;C operating temperature range],
      [10kA ampere interrupting capacity],
      [1A current rating],
      [Medium time delay],
    ),
  ),
  component(
    manufacturer: "Hubbel",
    catalog: "GFRST15W",
    qty: "1",
    sheet: 9,
    description: "Duplex GFCI Receptacle, 15A",
    tags: ("RECP1208",),
    specs: (
      [125VAC nominal supply voltage],
      [15A nominal current rating],
      [2-pole, 3-wire grounding],
      [5-15R outlet],
      [White receptacle color],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "RXM2AB2F7",
    qty: "10",
    sheet: 10,
    description: "Miniature Relay, 120VAC, 8 Blade",
    tags: ("CR1203", "CR1206", "CR1702", "CR1703", "CR1704", "CR1705", "CR1706", "CR1707", "CR1708", "CR1709",),
    specs: (
      [120VAC control circuit voltage],
      [10A continuous output current],
      [12A rated operational current],
      [Miniature relay type with status LED],
      [Lockable test button control type],
      [2 C/O contact composition],
      [100,000 cycles resistive electrical durability],
      [1.2VA average coil consumption],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "RXZE2M114",
    qty: "10",
    sheet: 10,
    description: "Miniature Relay Socket, 120VAC, DIN",
    tags: ("CR1203", "CR1206", "CR1702", "CR1703", "CR1704", "CR1705", "CR1706", "CR1707", "CR1708", "CR1709",),
    specs: (
      [For RXM 2 C/O series plug-in relay],
      [10A conventional free air thermal current],
      [< 300V UL rated operational voltage],
    ),
  ),
  component(
    manufacturer: "Ventev",
    catalog: "T09060010006HM",
    qty: "1",
    sheet: 11,
    description: "Cellular Antenna",
    tags: ("ANTENNA",),
    specs: (
      [824~960 MHz frequency range],
      [136MHz bandwidth],
      [6dBi gain],
      [360#sym.degree horizontal beamwidth, 30#sym.degree vertical beamwidth],
      [50#sym.Omega nominal impedance],
      [100W maximum power rating],
      [Vertical polarization],
      [N-Style female jack connector],
      [60m/s rated wind velocity],
      [Fiberglass radome],
      [-22#sym.degree;F~158#sym.degree;F operating temperature range],
    ),
  ),
  component(
    manufacturer: "Moxa",
    catalog: "EDS-205",
    qty: "1",
    sheet: 12,
    description: "Unmanaged Ethernet Switch, 5 Port",
    tags: ("ETH1403",),
    specs: (
      [5 10/100BaseT(X) RJ45 ports],
      [24VDC input operating voltage],
      [0.77W maximum power consumption],
      [Plastic, IP30 rated housing],
      [14 to 140#sym.degree;F operating temperature range],
    ),
  ),
  component(
    manufacturer: "Mersen",
    catalog: "MI5HF25V2/100",
    qty: "2",
    sheet: 13,
    description: "Miniature Fuse, Fast Acting, 2A",
    tags: ("FU1403", "FU1407",),
    specs: (
      [2A current rating],
      [5 mm x 20 mm size],
      [1500A breaking capacity at 250VAC],
      [1.17W loss at 100% In],
      [0.17V maximum voltage drop],
    ),
  ),
  component(
    manufacturer: "Mersen",
    catalog: "MI5HF25V0.5/100",
    qty: "4",
    sheet: 13,
    description: "Miniature Fuse, Fast Acting, 0.5A",
    tags: ("FU1501", "FU1520", "FU1601", "FU1920"),
    specs: (
      [0.5A current rating],
      [5 mm x 20 mm size],
      [1500A breaking capacity at 250VAC],
      [0.2W loss at 100% In],
      [0.01V maximum voltage drop],
    ),
  ),
  component(
    manufacturer: "Mersen",
    catalog: "GGM3",
    qty: "8",
    sheet: 13,
    description: "Fast Blow Fuse, 3A",
    tags: ("FU1758", "FU1759", "FU1760", "FU1761", "FU1762", "FU1763", "FU1764", "FU1765",),
    specs: (
      [Glass body],
      [5 mm x 20 mm size],
      [10kA I.R. at 125VAC],
      [3A current rating],
    ),
  ),
  component(
    manufacturer: "Phoenix Contact",
    catalog: "3046100",
    qty: "14",
    sheet: 13,
    description: "Fuse Terminal Block, 120VAC",
    tags: ("FU1758", "FU1759", "FU1760", "FU1761", "FU1762", "FU1763", "FU1764", "FU1765", "FU1501", "FU1520", "FU1601", "FU1403", "FU1407", "FU1920",),
    specs: (
      [Category III overvoltage protection],
      [4kV rated surge voltage],
      [1.02W maximum power dissipation for nominal condition],
      [For G / 5x20 fuses],
      [110VAC...250VAC LED voltage range],
    ),
  ),
  component(
    manufacturer: "Hoffman",
    catalog: "ALFSWD",
    qty: "2",
    sheet: 14,
    description: "Remote Door Switch",
    tags: ("LS1205",),
    specs: (
      [NEMA 4X rated door switch assembly],
      [Mounts on enclosure frame and includes mounted hardware],
      [14ga. steel mounting plate with a plated finish],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "BMXCPS3500H",
    qty: "1",
    sheet: 15,
    description: "Power Supply Module",
    tags: ("PWS1301",),
    specs: (
      [Modicon X80 power supply module],
      [100...240VAC primary voltage],
      [23.4W, 24VDC secondary power to I/O module and processor],
      [0.12kVA apparent power],
      [30A inrush current at 120VAC],
      [1.3A current at 24VDC secondary voltage],
      [8.5W maximum power dissipation],
      [Reset push-button cold restart],
      [1 green rack voltage OK LED],
      [1 green sensor voltage LED],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "HMIDT752",
    qty: "1",
    sheet: 16,
    description: "Operator Interface Terminal",
    tags: ("OIT",),
    specs: (
      [Harmony GTU product range],
      [Flat, touchscreen display],
      [24VDC rated supply voltage],
      [17W power consumption],
      [30A inrush current],
      [USB 2.0 type A and USB 2.0 type mini B integrated connection types],
      [2048x2048 touchscreen resolution],
      [1366x768 pixel resolution],
      [15.6 inch display size],
      [4:3 aspect ration],
      [50,000 hour backlight lifespan],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "HMIG2U",
    qty: "1",
    sheet: 16,
    description: "Display Base Unit",
    tags: ("OIT",),
    specs: (
      [Harmony GTU product range],
      [24VDC rated supply voltage],
      [Ethernet TCP/IP 2 RJ45, COM1 serial link RS232C, COM2 serial link RS485 RJ45, 2 USB 2.0 type A, USB 2.0 type mini B integrated connection types],
      [Modbus, Modbus TC/IP, Uni-Telway communication port protocal],
      [ARM Cortex-A9 processor],
      [1GB built-in flash memory],
      [1 SD card slot],
      [256 MB RAM internal, 512KB NVRAM backup memory],
      [Built-in realtime clock],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "VJDBTPRO3P",
    qty: "1",
    sheet: 16,
    description: "HMI Software",
    tags: ("OIT",),
    specs: (
      [Vijeo Designer configuration software],
      [3 station group license],
      [Windows 10 professional 32/64 bit or Windows 11 OS requirement],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "BMXP342020H",
    qty: "1",
    sheet: 17,
    description: "Processor",
    tags: ("CONTROLLER",),
    specs: (
      [Modicon M340 automation platform],
      [Processor module for severe environments],
      [1024 discrete I/O processor capacity],
      [256 analog I/O processor capacity],
      [2 Ethernet communication ports],
      [4096kB internal RAM (256kB for data, 3584kB for program constants and symbols)],
      [-13...158#sym.degree;F ambient air temperature range for operation],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "CEXSPUCZSGPAZZ",
    qty: "1",
    sheet: 17,
    description: "Modicon PLC Software",
    tags: ("CONTROLLER",),
    specs: (
      [EcoStruxture Control Expert License],
      [Service pack base, V16],
      [Control expert small],
      [3 user license group],
      [Windows 10/11, Windows Server 2019/2022 operating system requirement],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "BMXXBP1200H",
    qty: "1",
    sheet: 18,
    description: "Backplane, 12 Slots",
    tags: ("BACKPLANE",),
    specs: (
      [Ruggedized backplane for severe environments],
      [12 bus slots],
      [Compatible with BMXP34 processor],
      [0.83W power consumption],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "BMXFTB2000",
    qty: "6",
    sheet: 19,
    description: "Terminal Block, 20 Pin",
    tags: ("PLC1502", "PLC1521", "PLC1602", "PLC1701", "PLC1901", "PLC1925"),
    specs: (
      [20 terminal cage clamp removable terminal block],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "BMXFTB2800",
    qty: "1",
    sheet: 19,
    description: "Terminal Block, 20 Pin",
    tags: ("PLC1802",),
    specs: (
      [28 terminal cage clamp removable terminal block],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "BMXDAI1604H",
    qty: "3",
    sheet: 20,
    description: "Discrete Input Module, 120VAC",
    tags: ("PLC1502", "PLC1521", "PLC1602"),
    specs: (
      [120VAC discrete input voltage],
      [16 isolated discrete inputs for severe environments],
      [50/60Hz network frequency],
      [13k#sym.Omega input impedance],
      [3.8W power dissipation],
      [Capacitive input type],
      [5mA discrete input current],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "BMXDRA0815H",
    qty: "1",
    sheet: 21,
    description: "Discrete Output Module",
    tags: ("PLC1701",),
    specs: (
      [120VAC discrete output voltage],
      [8 relay discrete output module for severe environments],
      [50/60Hz network frequency],
      [3.6W power dissipation],
      [1780VAC 50/60Hz 1 min dielectric strength],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "BMXAMI0810H",
    qty: "1",
    sheet: 22,
    description: "Analog Input Module",
    tags: ("PLC1802",),
    specs: (
      [8 analog input module for severe environments],
      [4...20mA analog input type],
      [16 bit analog/digital conversion],
      [15 bits + sign analog input resolution],
      [#sym.plus.minus 30mA permitted overload on inputs],
      [First order digital filtering],
      [0.15% of full scale measurement error, 4...20mA 25#sym.degree;C],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "BMXAMO0410H",
    qty: "1",
    sheet: 23,
    description: "Analog Output Module",
    tags: ("PLC1901",),
    specs: (
      [4 analog input module for severe environments],
      [4...20mA analog output type],
      [15 bits + sign analog input resolution],
      [3W power consumption typical at 24VDC],
      [140mA current consumption at 24VDC],
      [Open circuit detection],
    ),
  ),
  component(
    manufacturer: "Modicon",
    catalog: "BMXDDI1602H",
    qty: "1",
    sheet: 24,
    description: "Discrete Input Module, 24VDC",
    tags: ("PLC1925",),
    specs: (
      [24VDC discrete input voltage],
      [16 isolated discrete inputs for severe environments],
      [Reverse polarity input protection],
      [6.8k#sym.Omega input impedance],
      [2.5W power dissipation],
      [Paralleling of inputs],
      [3.5mA discrete input current],
    ),
  ),
  component(
    manufacturer: "Phoenix Contact",
    catalog: "2865366",
    qty: "1",
    sheet: 24,
    description: "IS Barrier/Splitter",
    tags: ("ISB1432",),
    specs: (
      [Single channel repeater power supply],
      [3-way electrical isolation],
      [Category II overvoltage protection],
      [24VDC nominal supply voltage],
      [< 1.45W power dissipation],
      [#sym.lt.eq 1.8W power consumption],
    ),
  ),
  component(
    manufacturer: "Polyphaser",
    catalog: "IS-50NX-C2",
    qty: "1",
    sheet: 25,
    description: "Coaxial RF Surge Protector",
    tags: ("SP1402",),
    specs: (
      [125...1,000MHz frequency range],
      [50#sym.Omega impedance],
      [0.1dB insertion loss],
      [50kA surge current],
      [220#sym.mu;J throughput energy at 3kA],
      [375W at 125VAC input power to 220MHz],
      [N female to N female connectors],
    ),
  ),
  component(
    manufacturer: "Ventev",
    catalog: "LMR195NMSM-6",
    qty: "1",
    sheet: 27,
    description: "SMA Jumper Cable",
    tags: ("CBL1402",),
    specs: (
      [N male to SMA male connector],
      [General purpose fire rating],
      [No fire retardant],
      [Black jacket color],
      [Straight-straight connector body style],
      [Not UV resistant or rated for direct burial],
      [6ft jumper length],
    ),
  ),
  component(
    manufacturer: "Amphenol",
    catalog: "LDF4-50A",
    qty: "1",
    sheet: 26,
    description: "Coaxial Cable",
    tags: ("CBL1402A",),
    specs: (
      [Black jacket color],
      [50#sym.Omega #sym.plus.minus 1#sym.Omega cable impedance],
      [23.104 pF/ft capacitance],
      [0.451#sym.Omega/kft inner conductor resistance],
      [0.82#sym.Omega/kft outer conductor resistance],
      [0.058#sym.mu;H/ft inductance],
      [100000 M#sym.Omega;-km insulation resistance],
      [1-8800MHz operating frequency band],
      [40kW peak power],
      [Attenuation values typical, guaranteed within 5%],
    ),
  ),
  component(
    manufacturer: "Finder",
    catalog: "7T.81.0.000.2403",
    qty: "1",
    sheet: 28,
    description: "Enclosure Heater Thermostat, NC",
    tags: ("THERMOSTAT",),
    specs: (
      [1 NC SPST contact configuration],
      [10A rated current, 20A maximum peak current],
      [0.3A breaking capacity at 110VAC],
      [Silver Nickel standard contact material],
      [0...60#sym.degree;C setting range],
      [7#sym.plus.minus;4K switch differential],
      [$100*10^13$ cycle electrical life at 2500VA load],
      [IP20 protection category],
      [-45...80#sym.degree;C ambient temperature range],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-TSH75",
    qty: "1",
    sheet: 28,
    description: "Enclosure Heater",
    tags: ("HTR1206",),
    specs: (
      [Positive temperature coefficient application],
      [Designed for protection against condensation and corrosion],
      [35mm DIN rail clip for mounting],
      [120VAC supply voltage],
      [Touch safe, with 2 screw terminals for standard 14 AWG wire],
    ),
  ),
)

#let spare_parts = components.filter(comp => comp.catalog == "test2" or comp.catalog == "test")

#let spare_parts_qty = (
  "test": "1",
  "test2": "2"
)
