#import "definitions.typ": *

#let components = (
  component(
    manufacturer: "SCE",
    catalog: "SCE-36XEL3112SS6LP",
    qty: 1,
    sheet: 1,
    description: "Wall Mount Enclosure - NEMA 4X",
    tags: ("ENC",),
    specs: (
      [0.075" stainless steel type 304],
      [Continuously welded seams ground smooth],
      [Stainless steel concealed hinges],
      [Pour in place oil and water resistant gasket],
      [Ground studs on door and body],
      [Flange trough collar around all sides of door opening],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-36P30",
    qty: 1,
    sheet: 1,
    description: "Enclosure Backpanel",
    tags: ("ENC",),
    specs: (
      [Subpanel, bent],
      [Powder coated white finish],
      [33"H x 27"W x 0.88"D],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-ELMFK4",
    qty: 1,
    sheet: 1,
    description: "Wall Mount Foot Kit",
    tags: ("ENC",),
    specs: (
      [Made with chemical and corrosion resistant polyamide material],
      [Rated for NEMA 4X],
      [Stainless steel bolt and zinc nuts to maintain NEMA 4X enclosure rating],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "9422A2",
    qty: 1,
    sheet: 2,
    description: "Flange Mounted Disconnect Handle - NEMA 4X",
    tags: ("DISC",),
    specs: (
      [Flange mounted disconnect handle],
      [6 in. handle mechanism],
      [Variable depth disconnect switch],
      [For NEMA 4X enclosure, NEMA 4X rated],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "9422CSB30",
    qty: 1,
    sheet: 2,
    description: "Cable Operated Disconnect Mechanism",
    tags: ("DISC",),
    specs: (
      [Single cable operating mechanism],
      [For PowerPact B 3 circuit breakers],
      [36" cable length],
    ),
  ),
  component(
    manufacturer: "Trumeter",
    catalog: "722-0001",
    qty: 1,
    sheet: 3,
    description: "Elapsed Time Meter",
    tags: ("ETM",),
    specs: (
      [120VAC 50/60Hz operating voltage],
      [6 Figure display, 99999.9],
      [0.14" figure height],
      [Hours and indicator - white on black, Decimal - black on white],
      [Quartz accuracy],
      [Non-reset],
      [Black polymer case material],
      [Polymer lens material],
      [#sym.plus.minus 0.02% accuracy over entire range],
    ),
  ),
  component(
    manufacturer: "Trumeter",
    catalog: "5003-010",
    qty: 1,
    sheet: 3,
    description: "Gasket, Rectangular, 2-Hole",
    tags: ("ETM",),
    specs: (
      [NEMA 4X rated],
      [For Trumeter 722-0001 elapsed time meter],
      [2-hole rectangular gasket],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKT38LGG31",
    qty: 1,
    sheet: 4,
    description: "PTT Light, 120VAC LED, Green",
    tags: ("LT0330",),
    specs: (
      [Push-to-test pilot light],
      [Spring return operator type],
      [Green projecting, unmarked operator profile],
      [Plastic bezel material],
      [120VAC rated supply voltage],
      [0.55A rated operational current],
      [1 C/O contact],
      [Silver alloy contact material],
      [60kA rated short-circuit making capacity],
      [6kA rated breaking capacity],
      [Green fresnel polycarbonate lens],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKT38LRR31",
    qty: 1,
    sheet: 4,
    description: "PTT Light, 120VAC LED, Red",
    tags: ("LT0335",),
    specs: (
      [Push-to-test pilot light],
      [Spring return operator type],
      [Red projecting, unmarked operator profile],
      [Plastic bezel material],
      [120VAC rated supply voltage],
      [0.55A rated operational current],
      [1 C/O contact],
      [Silver alloy contact material],
      [60kA rated short-circuit making capacity],
      [6kA rated breaking capacity],
      [Red fresnel polycarbonate lens],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKT38LYA31",
    qty: 3,
    sheet: 4,
    description: "PTT Light, 120VAC LED, Amber",
    tags: ("LT0402", "LT0408", "LT0409",),
    specs: (
      [Push-to-test pilot light],
      [Spring return operator type],
      [Amber projecting, unmarked operator profile],
      [Plastic bezel material],
      [120VAC rated supply voltage],
      [0.55A rated operational current],
      [1 C/O contact],
      [Silver alloy contact material],
      [60kA rated short-circuit making capacity],
      [6kA rated breaking capacity],
      [Amber fresnel polycarbonate lens],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKR1B",
    qty: 1,
    sheet: 5,
    description: "Pushbutton, Black",
    tags: ("PB0310",),
    specs: (
      [Plastic bezel material],
      [Octagonal shape of signaling unit head],
      [Without contact block and light source],
      [NEMA 4X rated degree of protection],
      [Black operator color],
      [Flush operator profile],
      [Spring return operator],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001KA2",
    qty: 1,
    sheet: 5,
    description: "1 NO Contact",
    tags: ("PB0310",),
    specs: (
      [1 NO contact composition],
      [Standard contact operation],
      [Silver alloy contact material],
      [10A conventional free air thermal current],
      [0.55A rated operation current],
      [120VAC rated operational voltage],
      [60kA rated short-circuit making capacity],
      [6kA rated breaking capacity],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001KA3",
    qty: 2,
    sheet: 5,
    description: "1 NC Contact",
    tags: ("PB0310",),
    specs: (
      [1 NC contact composition],
      [Standard contact operation],
      [Silver alloy contact material],
      [10A conventional free air thermal current],
      [0.55A rated operation current],
      [120VAC rated operational voltage],
      [60kA rated short-circuit making capacity],
      [6kA rated breaking capacity],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKS43BH2",
    qty: 1,
    sheet: 6,
    description: "3 Position Switch, Black",
    tags: ("SS0321",),
    specs: (
      [Plastic bezel material],
      [3 position, 2 C/O contact composition],
      [Standard handle operator profile],
      [Black operator color],
      [Stay put operator type],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "9070TF150D1",
    qty: 1,
    sheet: 7,
    description: "CPT-480/120V, 150VA",
    tags: ("T0315",),
    specs: (
      [480VAC primary, 120VAC secondary voltage],
      [Accepts CC fuse types],
      [Screw clamp terminal electrical connection],
      [Copper winding material],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "BDL36020",
    qty: 1,
    sheet: 8,
    description: "Main Circuit Breaker, 20A",
    tags: ("CB0301",),
    specs: (
      [20A line rated current],
      [3 pole circuit breaker, toggle control type],
      [18kA breaking capacity],
      [Thermal magnetic trip unit technology],
      [80% continuous current rating],
      [44.3 lbf.in tightening torque],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "9926251002",
    qty: 1,
    sheet: 9,
    description: "Circuit Breaker, 120VAC, 2A",
    tags: ("CB0319",),
    specs: (
      [120VAC 50/60Hz nominal supply voltage],
      [2A rated current],
      [10kA interrupting capacity],
      [1500V, 50/60Hz dialectric strength],
      [100M#sym.Omega insulation resistance],
      [10,000 mechanical operation operating life],
      [-40-60#sym.degree C operating temperature],
      [20lb-in tightening torque],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "RXM2AB2F7",
    qty: 4,
    sheet: 10,
    description: "Miniature Relay, 120VAC, 8 Blade",
    tags: ("CR0324", "CR0332", "CR0336", "CR0401",),
    specs: (
      [Miniature plug-in relay],
      [2 C/O contacts],
      [With status LED and lockable test button],
      [120VAC control circuit voltage],
      [10A continuous output current],
      [12A rated operational current],
      [100000 cycles resistive electrical durability],
      [1.2VA average power consumption],
      [Silver nickel contact material],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "RXZE2M114",
    qty: 4,
    sheet: 10,
    description: "Relay Socket, 120VAC, 8 Blade, DIN",
    tags: ("CR0324", "CR0332", "CR0336", "CR0401",),
    specs: (
      [For miniature plug-in relay RXM, 2 C/O contact composition],
      [Screw clamp terminals, clip-on DIN rail mounting],
      [Mixed contact terminal arrangement],
      [< 300VAC UL rated operational voltage],
    ),
  ),
  component(
    manufacturer: "Mersen",
    catalog: "ATMR2",
    qty: 1,
    sheet: 11,
    description: "Fuse, Fast Acting, 2A",
    tags: ("FU0315B",),
    specs: (
      [Fast acting, very current limiting],
      [200kA I.R. AC rating],
      [For individual component and branch circuit protection],
      [600VAC voltage rating],
    ),
  ),
  component(
    manufacturer: "Mersen",
    catalog: "ATMR1/2",
    qty: 4,
    sheet: 11,
    description: "Fuse, Fast Acting, 0.5A",
    tags: ("FU0304", "FU0304A", "FU0305", "FU0305A",),
    specs: (
      [Fast acting, very current limiting],
      [200kA I.R. AC rating],
      [For individual component and branch circuit protection],
      [600VAC voltage rating],
    ),
  ),
  component(
    manufacturer: "Mersen",
    catalog: "ATQR8/10",
    qty: 2,
    sheet: 11,
    description: "Fuse, Time Delay, 0.8A",
    tags: ("FU0315", "FU0315A",),
    specs: (
      [Time delay, class CC fuse],
      [200kA I.R. AC rating],
      [For control transformer inrush loads],
      [Highly current limiting for low peak let-thru current],
      [600VAC voltage rating],
      [High-grade silica filler for fast arc quenching and high current limitation],
    ),
  ),
  component(
    manufacturer: "Mersen",
    catalog: "30324R",
    qty: 1,
    sheet: 11,
    description: "Class CC Fuse Block, 4 Poles",
    tags: ("BLOCK",),
    specs: (
      [Pressure plate with double quick-connects],
      [600VAC voltage rating],
      [30A maximum current],
      [10kA SCCR when using quick connect terminal],
      [Tin-plated copper alloy fuse clips],
      [20in-lb tightening torque],
    ),
  ),
  component(
    manufacturer: "Citel",
    catalog: "DS43S-480",
    qty: 1,
    sheet: 12,
    description: "Transient Voltage Surge Suppressor",
    tags: ("TVSS",),
    specs: (
      [120kA total maximum discharge current],
      [480VAC rated voltage],
      [-35-60#sym.degree C ambient temperature range],
      [100kA SCCR rating],
      [DIN rail mounting],
      [IP20 environmental rating],
      [-40/85#sym.degree F operating temperature min/max]
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "ATS490D17Y",
    qty: 1,
    sheet: 13,
    description: "Reduced Voltage Soft Starter",
    tags: ("RVSS",),
    specs: (
      [Soft starter for asynchronous motors],
      [480VAC power supply voltage],
      [Normal duty, 17A rated operational current],
      [Heavy duty, 12A rated operation current],
      [IP20 degree of protection],
      [7.5kW/5.5kW in motor supply line for normal/heavy duty],
      [10/7.5 maximum horsepower rating for normal/heavy duty operation],
      [120VAC control circuit voltage],
    ),
  ),
  component(
    manufacturer: "Socomec",
    catalog: "48290000",
    qty: 1,
    sheet: 14,
    description: "Modbus Power Meter",
    tags: ("PWS0306",),
    specs: (
      [Modbus RTU communication protocols],
      [RS485 communication ports],
      [50-300VAC max voltage (phase/neutral)],
      [14-158#sym.degree F operating temperature],
      [2 digital inputs],
      [4 voltage and current measurement inputs],
      [IP20 degree of protection on front side],
    ),
  ),
  component(
    manufacturer: "Socomec",
    catalog: "48290030",
    qty: 1,
    sheet: 14,
    description: "Digital I/O Power Meter Module",
    tags: ("PWS0306",),
    specs: (
      [Digital input/output module for DIRIS B power meter],
      [Provides 2 digital inputs and 2 digital outputs],
      [-4-122#sym.degree F operating temperature],
    ),
  ),
  component(
    manufacturer: "Socomec",
    catalog: "48290555",
    qty: 3,
    sheet: 14,
    description: "Split Core TR-10 Sensor, 25-63A",
    tags: ("PWS0306",),
    specs: (
      [TR-10 split-core current sensors for DIRIS B power monitoring devices],
      [Attachable current transformer],
      [25-63A rated current - 0.5-75A actual coverage range],
      [RJ12 connection type],
      [300VAC max voltage (phase/neutral)],
      [CAT III measurement category],
      [14-158#sym.degree F operating temperature],
    ),
  ),
  component(
    manufacturer: "Socomec",
    catalog: "48290584",
    qty: 1,
    sheet: 14,
    description: "RJ12 Connection Cable, 3 Count",
    tags: ("PWS0306",),
    specs: (
      [Red, Black, Yellow cable colors],
      [RJ12 connector],
      [2m cable length],
      [Connection cable for TR current sensors],
      [Grey color outer sheath],
      [26AWG size],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "9050JCK13V20",
    qty: 2,
    sheet: 15,
    description: "Timing Relay, 0-60 Sec, 120VAC, 8 Pin Octal, DPDT",
    tags: ("TR0316", "TR0405",),
    specs: (
      [120VAC rated supply voltage],
      [On-delay timer, 0.6-60 second range],
      [2VA power consumption],
      [10 current rating],
      [DPDT, 2 NO + 2 NC contact composition],
      [Silver nickel contact material],
      [Socket mounting type],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "8501NR51",
    qty: 2,
    sheet: 15,
    description: "Relay Socket, 120VAC, 8 Pin Octal, DIN",
    tags: ("TR0316", "TR0405",),
    specs: (
      [15A 300VAC rated current],
      [DIN rail mounting type],
      [Single tiered screw clamp terminal connection],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "9050JCK23V20",
    qty: 2,
    sheet: 16,
    description: "Timing Relay, 0-60 Sec, 120VAC, 11 Pin Octal, DPDT",
    tags: ("TR0407", "TR0409",),
    specs: (
      [120VAC rated supply voltage],
      [Off-delay timer, 0.6-60 second range],
      [2VA power consumption],
      [10 current rating],
      [DPDT, 2 NO + 2 NC contact composition],
      [Silver nickel contact material],
      [Socket mounting type],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "8501NR61",
    qty: 2,
    sheet: 16,
    description: "Relay Socket, 120VAC, 11 Pin Octal, DIN",
    tags: ("TR0407", "TR0409",),
    specs: (
      [15A 300VAC rated current],
      [DIN rail mounting type],
      [Single tiered screw clamp terminal connection],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-TSH50",
    qty: 1,
    sheet: 17,
    description: "Enclosure Heater",
    tags: ("HTR0319",),
    specs: (
      [DIN rail clip mounting],
      [Designed for protection from low temperatures, condensation and corrosion],
      [Touch safe heater],
      [120VAC rated operational voltage],
      [2 screw terminal connection style],
    ),
  ),
  component(
    manufacturer: "Finder",
    catalog: "7T.81.0.000.2403",
    qty: 1,
    sheet: 17,
    description: "Enclosure Heater Thermostat, NC",
    tags: ("Thermostat",),
    specs: (
      [7T - 7T series thermostat],
      [8 - Temperature control thermostat],
      [1 - 1 contact],
      [0 - No operating voltage required],
      [000 - No operating voltage required],
      [2 - Temperature control],
      [4 - 1 NC contact],
      [03 - 0-60#sym.degree C temperature control range],
      [IP20 protection category],
      [Silver nickel standard contact material],
    ),
  ),
)
