#import "definitions.typ": *

#let components = (
  component(
    manufacturer: "SCE",
    catalog: "SCE-24H2010SS6LP",
    qty: "1",
    sheet: 1,
    description: "Wall Mount Enclosure - NEMA 4X",
    tags: ("ENC",),
    specs: (
      [0.075" stainless stell type 316/316L],
      [Flange trough collar around all sides of door opening],
      [Pour in place oil & water resistant gasket],
      [Stainless stell continuous hinges],
      [Hasp and staple for padlocking],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-24P20",
    qty: "1",
    sheet: 1,
    description: "Enclosure Backpanel",
    tags: ("ENC",),
    specs: (
      [21"H x 17"W x .88"D],
      [Powder coated white finish],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKT38LWW31",
    qty: "1",
    sheet: 2,
    description: "PTT Light, 120VAC LED, White",
    tags: ("LT4203",),
    specs: (
      [Fresnel plastic lens type],
      [Full voltage 120V light block supply],
      [Plastic bezel material],
      [White lens color],
      [White LED],
      [Round signaling unit head],
      [Polycarbonate lens material],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKT38LYA31",
    qty: "2",
    sheet: 2,
    description: "PTT Light, 120VAC LED, Amber",
    tags: ("LT4307", "LT4311",),
    specs: (
      [Fresnel plastic lens type],
      [Full voltage 120V light block supply],
      [Plastic bezel material],
      [Amber lens color],
      [Yellow LED],
      [Round signaling unit head],
      [Polycarbonate lens material],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001SKR1B",
    qty: "1",
    sheet: 3,
    description: "Pushbutton, Black",
    tags: ("PB4306", ),
    specs: (
      [Plastic bezel material],
      [Octagonal signaling unit head],
      [NEMA 4X degree of protection],
      [Black operator color],
      [Flush operator profile],
      [Spring return operator],
      [30mm size],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "9001KA3",
    qty: "1",
    sheet: 3,
    description: "1 NC Contact",
    tags: ("PB4306", ),
    specs: (
      [Positived opening contact operation],
      [Screw clamp terminals],
      [7.08 lbf.in tightening torque],
      [Silver alloy contact material],
      [10A conventional free air thermal current],
      [0.55A rated operational current],
      [60kA rated short-circuit making capacity],
      [6kA rated breaking capacity],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "9926251005",
    qty: "1",
    sheet: 4,
    description: "Circuit Breaker, 120VAC, 5A",
    tags: ("CB4202", ),
    specs: (
      [120VAC operational voltage],
      [Hydraulic magnetic type circuit breaker],
      [5A current rating],
      [10kA interrupting capacity],
      [100M#sym.Omega insulation resistance],
      [10000 mechanical operations operating life],
      [-40...65#sym.degree C operating temperature],
      [20in.-lb tightening torque],
    ),
  ),
  component(
    manufacturer: "Weidmuller",
    catalog: "9926251001",
    qty: "1",
    sheet: 4,
    description: "Circuit Breaker, 120VAC, 1A",
    tags: ("CB4202A", ),
    specs: (
      [120VAC operational voltage],
      [Hydraulic magnetic type circuit breaker],
      [1A current rating],
      [10kA interrupting capacity],
      [100M#sym.Omega insulation resistance],
      [10000 mechanical operations operating life],
      [-40...65#sym.degree C operating temperature],
      [20in.-lb tightening torque],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "RXM2AB2F7",
    qty: "9",
    sheet: 5,
    description: "Miniature Relay, 120VAC, 8 Blade",
    tags: ("CR4209", "CR4210",  "CR4223", "CR4225", "CR4226", "CR4306", "CR4310", "CR4316", "CR4317",),
    specs: (
      [120VAC operational voltage],
      [2 C/O contact configuration],
      [With status LED and lockable test button],
      [10A continuous output current],
      [12A conventional enclosed thermal current],
      [12A rated operational current],
      [100000 cycles resistive electrical durability],
      [Silver nickel contacts material],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "RXZE2M114",
    qty: "9",
    sheet: 5,
    description: "Miniature Relay Socket, 8 Blade, DIN",
    tags: ("CR4209", "CR4210",  "CR4223", "CR4225", "CR4226", "CR4306", "CR4310", "CR4316", "CR4317",),
    specs: (
      [120VAC operational voltage],
      [Compatible with RXM 2 C/O],
      [10A conventional free air thermal current],
      [< 300 V UL rated operational voltage],
      [Flat pin shape],
      [< 1 Nm M3 tightening torque],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "RXM3AB2F7",
    qty: "1",
    sheet: 6,
    description: "Miniature Relay, 120VAC, 11 Blade",
    tags: ("CR4301",),
    specs: (
      [120VAC operational voltage],
      [3 C/O contact configuration],
      [With status LED and lockable test button],
      [6.7A continuous output current],
      [10A conventional enclosed thermal current],
      [10A rated operational current],
      [100000 cycles resistive electrical durability],
      [Silver nickel contacts material],
    ),
  ),
  component(
    manufacturer: "Schneider Electric",
    catalog: "RXZE2S111M",
    qty: "1",
    sheet: 6,
    description: "Miniature Relay Socket, 11 Blade, DIN",
    tags: ("CR4301",),
    specs: (
      [120VAC operational voltage],
      [Compatible with RXM 3 C/O],
      [10A conventional free air thermal current],
      [< 300 V UL rated operational voltage],
      [Flat pin shape],
      [< 1 Nm M3 tightening torque],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "9050JCK16V20",
    qty: "1",
    sheet: 7,
    description: "Timing Relay, 0-10 min, 120VAC, 8 Pin Octal, DPDT",
    tags: ("TR4224",),
    specs: (
      [120VAC operational voltage],
      [0.1...10 min timing range],
      [2VA power consumption],
      [10A operational current rating],
      [DPDT, 2 NO + 2 NC contaction composition],
      [Silver nickel contact material],
    ),
  ),
  component(
    manufacturer: "Square D",
    catalog: "8501NR51",
    qty: "1",
    sheet: 7,
    description: "Timing Relay Socket, 8 Pin, DIN",
    tags: ("TR4224",),
    specs: (
      [120VAC operational voltage],
      [15A rated current],
      [Single tiered screw clamp terminal electrical connection],
    ),
  ),
  component(
    manufacturer: "Diversified",
    catalog: "ISO-120-AAE",
    qty: "2",
    sheet: 8,
    description: "Isolated Switch, 2 Channel",
    tags: ("ISR4206", "ISR4220",),
    specs: (
      [120VAC control voltage, 2 channel],
      [2.5VA power consumption],
      [20 million operations mechanical life expectancy],
      [50,000 operations at rated load electrical life expectancy],
      [-4#sym.degree to 131#sym.degree F operational temperature rating],
      [-40#sym.degree to 185#sym.degree F storage temperature rating],
      [Style "E" Lexan#sym.trademark.registered surface mounted],
    ),
  ),
  component(
    manufacturer: "Eaton",
    catalog: "D851LA",
    qty: "1",
    sheet: 9,
    description: "Alternating Relay",
    tags: ("AR4315",),
    specs: (
      [SPDT contact],
      [With ALTERNATE, LOAD A, LOAD B selector switcht],
      [120VAC control voltage],
      [Less than 3VA load],
      [10,000,000 operations mechanical life expectancy],
      [100,000 operations electrical life],
      [-20#sym.degree to 150#sym.degree F operating temperature range],
      [2 indicator LEDs for LOAD A and LOAD B],
    ),
  ),
  component(
    manufacturer: "Eaton",
    catalog: "D3PA2",
    qty: "1",
    sheet: 9,
    description: "Alternating Relay Socket",
    tags: ("AR4315",),
    specs: (
      [General-purpose relay socket],
      [D3 series socket],
      [DIN rail mounted socket],
      [10/15A nominal rated operational current],
      [Screw clamping wiring connection],
    ),
  ),
  component(
    manufacturer: "SCE",
    catalog: "SCE-TSH25",
    qty: "1",
    sheet: 10,
    description: "Enclosure Heater",
    tags: ("HTR4202",),
    specs: (
      [DIN rail clip for 35mm DIN rail],
      [Designed for protection from low temperatures, condensation, and corrosion],
      [Touch safe with 2 screw terminal for standard AWG 14 wire],
      [120VAC operational voltage],
    ),
  ),
  component(
    manufacturer: "Finder",
    catalog: "7T.81.0.000.2403",
    qty: "1",
    sheet: 10,
    description: "Enclosure Heater Thermostat, NC",
    tags: ("THERMOSTAT",),
    specs: (
      [-45...80#sym.degree C ambient temperature range],
      [1 NC contact configuration],
      [10A rated current for contacts],
      [0...60#sym.degree C temperature control range],
    ),
  ),
)

#let spare_parts = components.filter(comp => comp.catalog == "test2" or comp.catalog == "test")

#let spare_parts_qty = (
  "test": "1",
  "test2": "2"
)
